trigger:
  - feature/cgm/yaml-pipelines #master
  
pool:
  vmImage: 'ubuntu-latest'
  
variables:
  - group: Azure     
  - group: Infra.Dev
  
stages:
- stage: Build
  displayName: CI - Validate ARM Templates
  jobs:
  - job: Validate
    displayName: Validate ARM Templates
    steps:
    - template: templates/infra-build.yaml
- stage: Deploy
  displayName: Deploy to DEV
  jobs:
  - job: Deploy
    displayName: Deploy Infra
    steps:
    - template: templates/infra-deploy.yaml
    - template: templates/customers-api-deploy.yaml
    - template: templates/customers-api-deploy.yaml
