trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'
  
variables:
  - group: Azure     
  - group: Infra.Dev
  
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Validate
    displayName: Validate ARM Templates
    steps:
    - template: deploy/templates/infra-build.yaml

- stage: Deploy
  displayName: Release to DEV
  jobs:
  - job: Deploy
    displayName: Deploy Infra
    steps:
    - template: deploy/templates/infra-deploy.yaml
    - template: deploy/templates/customers-api-deploy.yaml
    - template: deploy/templates/customers-api-deploy.yaml
