steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: source/customers/ERP/Validation/'
  inputs:
    SourceFolder: source/customers/ERP
    Contents: '*.json'
    TargetFolder: 'source/customers/ERP/Validation/'
    CleanTargetFolder: true
    OverWrite: true

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in source/customers/ERP/Validation/*.json'
  inputs:
    rootDirectory: 'source/customers/ERP/Validation/'
    targetFiles: '**/*.json'    

- task: AzureResourceGroupDeployment@2
  displayName: 'Validate Customer Topic Subscription on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
  inputs:
    azureSubscription: '$(Azure.ServiceConnectionId)'
    resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
    location: '$(Infra.Location)'
    csmFile: 'source/infra/infra-service-bus-topic.json'
    csmParametersFile: 'source/customers/ERP/Validation/topic-subscription-customers.parameters.json'
    deploymentMode: Validation

- task: AzureResourceGroupDeployment@2
  displayName: 'Validate Customer Logic App on $(Infra.Environment)-demo-customers-erp-$(Infra.Region)'
  inputs:
    azureSubscription: '$(Azure.ServiceConnectionId)'
    resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
    location: '$(Infra.Location)'
    csmFile: 'source/customers/ERP/Validation/logicapp-customers-erp.json'
    csmParametersFile: 'source/customers/ERP/Validation/logicapp-customers-erp.parameters.json'
    deploymentMode: Validation

- task: AzureResourceGroupDeployment@2
  displayName: 'Validate Customer API on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
  inputs:
    azureSubscription: '$(Azure.ServiceConnectionId)'
    resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
    location: '$(Infra.Location)'
    csmFile: 'source/customers/ERP/Validation/apim-customers-erp-stub.json'
    csmParametersFile: 'source/customers/ERP/Validation/apim-customers-erp-stub.parameters.json'
    deploymentMode: Validation

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: source/customers/ERP
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true

- publish: source/customers/ERP
  artifact: ERP