parameters:
  name: ''
  pool: ''
  env: ''

jobs:
- deployment: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  displayName: Deploy ERP
  environment: '${{ parameters.env }}'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: ERP

        - download: Infra          

        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in $(Pipeline.Workspace)/ERP/*.json'
          inputs:
            rootDirectory: '$(Pipeline.Workspace)/ERP/'
            targetFiles: '**/*.json'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Customer Topic Subscription on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
          inputs:
            azureSubscription: '$(Azure.ServiceConnectionId)'
            resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
            location: '$(Infra.Location)'
            csmFile: '$(Pipeline.Workspace)/Infra/Infra/infra-service-bus-topic.json'
            csmParametersFile: '$(Pipeline.Workspace)/ERP/topic-subscription-customers.parameters.json'
            deploymentMode: Incremental

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Customer Logic App on $(Infra.Environment)-demo-customers-erp-$(Infra.Region)'
          inputs:
            azureSubscription: '$(Azure.ServiceConnectionId)'
            resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-demo-customers-erp-$(Infra.Region)'
            location: '$(Infra.Location)'
            csmFile: '$(Pipeline.Workspace)/ERP/logicapp-customers-erp.json'
            csmParametersFile: '$(Pipeline.Workspace)/ERP/logicapp-customers-erp.parameters.json'
            deploymentMode: Incremental

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Customer API on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
          inputs:
            azureSubscription: '$(Azure.ServiceConnectionId)'
            resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
            location: '$(Infra.Location)'
            csmFile: '$(Pipeline.Workspace)/ERP/apim-customers-erp-stub.json'
            csmParametersFile: '$(Pipeline.Workspace)/ERP/apim-customers-erp-stub.parameters.json'
            deploymentMode: Incremental
