steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: source/infra/Validation/'
  inputs:
    SourceFolder: source/infra
    Contents: '*.json'
    TargetFolder: 'source/infra/Validation/'
    CleanTargetFolder: true
    OverWrite: true

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in source/infra/Validation/*.json'
  inputs:
    rootDirectory: 'source/infra/Validation/'
    targetFiles: '**/*.json'

- task: AzureResourceGroupDeployment@2
  displayName: 'Validate infra-apim on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
  inputs:
    azureSubscription: '$(Azure.ServiceConnectionId)'
    resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
    location: '$(Infra.Location)'
    csmFile: 'source/infra/Validation/infra-apim.json'
    csmParametersFile: 'source/infra/Validation/infra-apim.parameters.json'
    deploymentMode: Validation

- task: AzureResourceGroupDeployment@2
  displayName: 'Validate infra-app-insights on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
  inputs:
    azureSubscription: '$(Azure.ServiceConnectionId)'
    resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
    location: '$(Infra.Location)'
    csmFile: 'source/infra/Validation/infra-app-insights.json'
    csmParametersFile: 'source/infra/Validation/infra-app-insights.parameters.json'
    deploymentMode: Validation    

- task: AzureResourceGroupDeployment@2
  displayName: 'Validate infra-key-vault on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
  inputs:
    azureSubscription: '$(Azure.ServiceConnectionId)'
    resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
    location: '$(Infra.Location)'
    csmFile: 'source/infra/Validation/infra-key-vault.json'
    csmParametersFile: 'source/infra/Validation/infra-key-vault.parameters.json'
    deploymentMode: Validation   
 
- task: AzureResourceGroupDeployment@2
  displayName: 'Validate infra-log-analytics on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
  inputs:
    azureSubscription: '$(Azure.ServiceConnectionId)'
    resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
    location: '$(Infra.Location)'
    csmFile: 'source/infra/Validation/infra-log-analytics.json'
    csmParametersFile: 'source/infra/Validation/infra-log-analytics.parameters.json'
    deploymentMode: Validation   

- task: AzureResourceGroupDeployment@2
  displayName: 'Validate infra-service-bus on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
  inputs:
    azureSubscription: '$(Azure.ServiceConnectionId)'
    resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
    location: '$(Infra.Location)'
    csmFile: 'source/infra/Validation/infra-service-bus.json'
    csmParametersFile: 'source/infra/Validation/infra-service-bus.parameters.json'
    deploymentMode: Validation

- task: AzureResourceGroupDeployment@2
  displayName: 'Validate infra-storage-account on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
  inputs:
    azureSubscription: '$(Azure.ServiceConnectionId)'
    resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
    location: '$(Infra.Location)'
    csmFile: 'source/infra/Validation/infra-storage-account.json'
    csmParametersFile: 'source/infra/Validation/infra-storage-account.parameters.json'
    deploymentMode: Validation    

- task: DeleteFiles@1
  displayName: 'Delete files from source/infra/Validation'
  inputs:
    SourceFolder: 'source/infra/Validation'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: source/infra
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true

- publish: source/infra
  artifact: infra