parameters:
  name: ''
  pool: ''
  env: ''

jobs:
- deployment: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  displayName: Deploy Infra
  environment: '${{ parameters.env }}'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: infra

        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in $(Pipeline.Workspace)/infra/*.json'
          inputs:
            rootDirectory: '$(Pipeline.Workspace)/infra'
            targetFiles: '**/*.json'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy infra-log-analytics on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
          inputs:
            azureSubscription: '$(Azure.ServiceConnectionId)'
            resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
            location: '$(Infra.Location)'
            csmFile: '$(Pipeline.Workspace)/infra/infra-log-analytics.json'
            csmParametersFile: '$(Pipeline.Workspace)/infra/infra-log-analytics.parameters.json'
            deploymentMode: Incremental   

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy infra-app-insights on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
          inputs:
            azureSubscription: '$(Azure.ServiceConnectionId)'
            resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
            location: '$(Infra.Location)'
            csmFile: '$(Pipeline.Workspace)/infra/infra-app-insights.json'
            csmParametersFile: '$(Pipeline.Workspace)/infra/infra-app-insights.parameters.json'
            deploymentMode: Incremental

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy infra-service-bus on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
          inputs:
            azureSubscription: '$(Azure.ServiceConnectionId)'
            resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
            location: '$(Infra.Location)'
            csmFile: '$(Pipeline.Workspace)/infra/infra-service-bus.json'
            csmParametersFile: '$(Pipeline.Workspace)/infra/infra-service-bus.parameters.json'
            deploymentMode: Incremental

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy infra-storage-account on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
          inputs:
            azureSubscription: '$(Azure.ServiceConnectionId)'
            resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
            location: '$(Infra.Location)'
            csmFile: '$(Pipeline.Workspace)/infra/infra-storage-account.json'
            csmParametersFile: '$(Pipeline.Workspace)/infra/infra-storage-account.parameters.json'
            deploymentMode: Incremental      

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy infra-key-vault on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
          inputs:
            azureSubscription: '$(Azure.ServiceConnectionId)'
            resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
            location: '$(Infra.Location)'
            csmFile: '$(Pipeline.Workspace)/infra/infra-key-vault.json'
            csmParametersFile: '$(Pipeline.Workspace)/infra/infra-key-vault.parameters.json'
            deploymentMode: Incremental  

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy infra-apim on $(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
          inputs:
            azureSubscription: '$(Azure.ServiceConnectionId)'
            resourceGroupName: '$(Infra.Environment)-$(Infra.Project)-infra-$(Infra.Region)'
            location: '$(Infra.Location)'
            csmFile: '$(Pipeline.Workspace)/infra/infra-apim.json'
            csmParametersFile: '$(Pipeline.Workspace)/infra/infra-apim.parameters.json'
            deploymentMode: Incremental
