name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      environment: dev
      project: demo
      region: ne
      location: northeurope

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az group create --name $environment-$project-infra-$region --location $location
          az deployment group validate --resource-group $environment-$project-infra-$region --template-file source/infra/infra-log-analytics.json --parameters source/infra/infra-log-analytics.parameters.json
