name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure Resource Manager (ARM) Template Deployment
      uses: whiteducksoftware/azure-arm-action-js@v1
      with:
        resourceGroupName: dev-demo-infra-ne
        templateLocation: source/infra/infra-log-analytics.json
        deploymentMode: Incremental
        deploymentName: infra-log-analytics
        parameters: source/infra/infra-log-analytics.parameters.json
