name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      environment: dev
      project: demo
      region: ne
      location: northeurope

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          az group create --name $environment-$project-infra-$region --location northeurope
          az deployment create --resource-group $environment-$project-infra-$region --template-file source/infra/infra-log-analytics.json --parameters source/infra/infra-log-analytics.parameters.json --location $location
    - name: Azure Resource Manager (ARM) Template Deployment
      uses: whiteducksoftware/azure-arm-action-js@v1
      with:
        resourceGroupName: $environment-$project-infra-$region
        templateLocation: source/infra/infra-log-analytics.json
        deploymentMode: Incremental
        deploymentName: infra-log-analytics
        parameters: source/infra/infra-log-analytics.parameters.json
